export const highlights = [
  { id: "test-id", title: "Free Parking" },
  { id: "test-id-1", title: "Free Food" },
  { id: "test-id-2", title: "Affordable Accomodation" },
  { id: "test-id-3", title: "Wi-Fi" },
];
export const reviewConstants = [
  {
    id: 1,
    reviewBody:
      "Delivery arrived late and items were missing. Customer support took forever to respond and didn’t resolve the issue properly.",
    starRating: 2,
    photoUrls: [
      "https://ik.imagekit.io/clerreview/images/media/auth_banner_3-1_pMk6jAWiX.jpg",
      "https://ik.imagekit.io/clerreview/images/media/auth_banner_2-2_iugTVjtSQ.jpg",
      "https://ik.imagekit.io/clerreview/images/media/auth_banner_2-1_eBrts85Ce.jpg",
      "https://ik.imagekit.io/clerreview/images/media/auth_banner_1-2_voHD8YBYm.jpg",
      "https://ik.imagekit.io/clerreview/images/media/auth_banner_1-1_tw9Ja7q4B.jpg",
    ],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-01T10:15:22.009+00:00",
    reviewSubject: "Late delivery issues",
    name: "Alex Morgan",
    reply: {
      name: "Aerglo Tech",
      body: "Hi, \n We sent a follow up mail, please reply to it.\n Thanks.",
      createdAt: "2025-12-03T10:15:22.009+00:00",
    },
  },
  {
    id: 2,
    reviewBody:
      "The app crashed twice while I was placing my order. By the time it worked, some items were already out of stock.",
    starRating: 2,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-02T11:02:41.009+00:00",
    reviewSubject: "App instability",
    name: null,
  },
  {
    id: 3,
    reviewBody:
      "Prices were much higher than in-store and the shopper replaced items without asking for approval.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-03T09:48:10.009+00:00",
    reviewSubject: "Unexpected substitutions",
    name: "Linda K",
  },
  {
    id: 4,
    reviewBody:
      "Customer service was polite but not helpful. I still haven’t received my refund after a week.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-03T15:30:55.009+00:00",
    reviewSubject: "Refund delay",
    name: "Michael B",
  },
  {
    id: 5,
    reviewBody:
      "Order was cancelled without explanation. I had to reorder and pay a higher delivery fee.",
    starRating: 1,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-04T08:11:02.009+00:00",
    reviewSubject: "Order cancelled",
    name: null,
  },
  {
    id: 6,
    reviewBody:
      "Some items were damaged on arrival. Packaging could definitely be improved.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-04T18:42:19.009+00:00",
    reviewSubject: "Damaged items",
    name: "Sarah J",
  },
  {
    id: 7,
    reviewBody:
      "Delivery was fast, but the shopper ignored my notes about preferred brands.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-05T12:25:44.009+00:00",
    reviewSubject: "Ignored instructions",
    name: "Daniel R",
  },
  {
    id: 8,
    reviewBody:
      "Promo code didn’t apply at checkout even though it showed as valid.",
    starRating: 2,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-05T19:09:33.009+00:00",
    reviewSubject: "Promo code issue",
    name: null,
  },
  {
    id: 9,
    reviewBody:
      "The shopper communicated well, but delivery time kept changing throughout the order.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-06T07:58:01.009+00:00",
    reviewSubject: "Unstable delivery time",
    name: "Emma L",
  },
  {
    id: 10,
    reviewBody:
      "Support chat disconnected mid-conversation and I had to start all over again.",
    starRating: 1,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-06T16:47:29.009+00:00",
    reviewSubject: "Poor support experience",
    name: "Chris T",
  },

  // --- continuing ---

  {
    id: 11,
    reviewBody:
      "Items were correct, but delivery fee was much higher than expected.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-07T10:14:52.009+00:00",
    reviewSubject: "High delivery fee",
    name: "Olivia S",
  },
  {
    id: 12,
    reviewBody:
      "Order arrived earlier than scheduled, which worked out fine for me.",
    starRating: 4,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-07T13:36:41.009+00:00",
    reviewSubject: "Early delivery",
    name: "James W",
  },
  {
    id: 13,
    reviewBody: "Some items were substituted with more expensive alternatives.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-08T09:01:18.009+00:00",
    reviewSubject: "Pricey substitutions",
    name: "Nina P",
  },
  {
    id: 14,
    reviewBody:
      "App is easy to use, but customer support response time is too slow.",
    starRating: 3,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-08T17:22:07.009+00:00",
    reviewSubject: "Slow customer support",
    name: null,
  },
  {
    id: 15,
    reviewBody: "Delivery driver was friendly and professional.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-09T11:55:49.009+00:00",
    reviewSubject: "Great delivery experience",
    name: "Victor H",
  },

  // --- remaining condensed for brevity but still unique ---

  {
    id: 16,
    reviewBody: "Order arrived cold and late.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-09T18:40:10.009+00:00",
    reviewSubject: "Late delivery",
    name: "Grace A",
  },
  {
    id: 17,
    reviewBody: "The app logged me out during checkout.",
    starRating: 1,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-10T08:21:37.009+00:00",
    reviewSubject: "Checkout issue",
    name: null,
  },
  {
    id: 18,
    reviewBody: "Everything arrived as expected.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-10T14:59:03.009+00:00",
    reviewSubject: "Smooth experience",
    name: "Paul D",
  },
  {
    id: 19,
    reviewBody: "Missing one item but refund was quick.",
    starRating: 4,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-10T19:33:55.009+00:00",
    reviewSubject: "Quick refund",
    name: "Sophia N",
  },
  {
    id: 20,
    reviewBody: "Delivery driver went to wrong address first.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-11T07:45:21.009+00:00",
    reviewSubject: "Wrong address",
    name: "Henry C",
  },
  {
    id: 1,
    reviewBody:
      "Their system claimed I had a previous account and then put me on hold for 20 minutes — only to disappear. Misleading promotion and terrible customer service. Very frustrating experience.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-11T16:43:57.009+00:00",
    reviewSubject: "Instacart bad service",
    name: "User One",
  },
  {
    id: 2,
    reviewBody:
      "I tried to use their 'first 3 free deliveries' promo, but even on my first order with a new email, I was charged a delivery fee.",
    starRating: 1,
    photoUrls: null,
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-12T16:43:57.009+00:00",
    reviewSubject: "Instacart bad service",
    name: null,
  },
  {
    id: 3,
    reviewBody:
      "Excellent service! My groceries arrived within 30 minutes, everything was fresh and exactly as ordered. Will definitely use again.",
    starRating: 5,
    photoUrls: ["receipt1.jpg", "groceries1.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-10T09:15:22.009+00:00",
    reviewSubject: "Fast delivery",
    name: "Sarah Johnson",
  },
  {
    id: 4,
    reviewBody:
      "Shopper replaced items without asking first. Got completely wrong brand of coffee and overripe bananas. Very disappointing.",
    starRating: 2,
    photoUrls: ["coffee_wrong.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-09T14:30:45.009+00:00",
    reviewSubject: "Wrong items delivered",
    name: "Mike Thompson",
  },
  {
    id: 5,
    reviewBody:
      "App keeps crashing at checkout. Tried three different devices and same issue. Lost my entire cart twice. Needs urgent fix.",
    starRating: 1,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-08T11:22:33.009+00:00",
    reviewSubject: "Technical issues",
    name: null,
  },
  {
    id: 6,
    reviewBody:
      "Best grocery delivery service I've used. Shopper communicated throughout and found all items. 10/10 experience!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-07T17:45:12.009+00:00",
    reviewSubject: "Great communication",
    name: "Emma Davis",
  },
  {
    id: 7,
    reviewBody:
      "Order was 45 minutes late with no communication. Frozen items were partially thawed when they arrived.",
    starRating: 2,
    photoUrls: ["melted_icecream.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-06T13:10:28.009+00:00",
    reviewSubject: "Late delivery",
    name: "Robert Chen",
  },
  {
    id: 8,
    reviewBody:
      "Prices are significantly higher than in-store. Paid $8 for cereal that costs $4.99 at the supermarket. Too expensive.",
    starRating: 2,
    photoUrls: ["price_comparison.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-05T10:05:17.009+00:00",
    reviewSubject: "Overpriced items",
    name: null,
  },
  {
    id: 9,
    reviewBody:
      "Shopper went above and beyond! Found all items, bagged everything perfectly, and delivered early. Tip well earned!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-04T15:20:39.009+00:00",
    reviewSubject: "Exceptional shopper",
    name: "Lisa Park",
  },
  {
    id: 10,
    reviewBody:
      "Missing 5 items from my order. Customer service offered $5 credit for $35 worth of missing groceries. Unacceptable.",
    starRating: 1,
    photoUrls: ["missing_items.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-03T12:30:55.009+00:00",
    reviewSubject: "Missing items",
    name: "David Wilson",
  },
  {
    id: 11,
    reviewBody:
      "Perfect for busy parents! Got my weekly groceries while working from home. Everything arrived fresh and on time.",
    starRating: 4,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-12-02T16:15:42.009+00:00",
    reviewSubject: "Time saver",
    name: "Jessica Miller",
  },
  {
    id: 12,
    reviewBody:
      "Charged twice for the same order. Been on hold for 45 minutes trying to get a refund. This is ridiculous.",
    starRating: 1,
    photoUrls: ["double_charge.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-12-01T11:40:18.009+00:00",
    reviewSubject: "Billing error",
    name: null,
  },
  {
    id: 13,
    reviewBody:
      "Regular user for 2 years. Consistently good service, occasional issues but always resolved quickly by support.",
    starRating: 4,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-30T14:25:33.009+00:00",
    reviewSubject: "Reliable service",
    name: "Thomas Anderson",
  },
  {
    id: 14,
    reviewBody:
      "Shopper didn't check expiration dates. Received milk expiring tomorrow and moldy berries. Quality control needed.",
    starRating: 2,
    photoUrls: ["moldy_strawberries.jpg", "expired_milk.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-29T09:55:47.009+00:00",
    reviewSubject: "Poor quality items",
    name: "Maria Garcia",
  },
  {
    id: 15,
    reviewBody:
      "Tip baiting is a problem here. Reduced tip after delivery for no reason. Shoppers deserve better treatment.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-28T18:20:14.009+00:00",
    reviewSubject: "Tip reduction issue",
    name: null,
  },
  {
    id: 16,
    reviewBody:
      "Love the bulk buying option! Saved 20% on paper products and canned goods. Great for stocking up.",
    starRating: 5,
    photoUrls: ["bulk_items.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-27T13:45:29.009+00:00",
    reviewSubject: "Good for bulk purchases",
    name: "James Taylor",
  },
  {
    id: 17,
    reviewBody:
      "App navigation is confusing. Too many clicks to find what I need. Interface needs redesign for better UX.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-26T10:30:52.009+00:00",
    reviewSubject: "Poor app design",
    name: "Amanda Lee",
  },
  {
    id: 18,
    reviewBody:
      "Delivered to wrong address three times. How hard is it to read an address? Waste of my entire afternoon.",
    starRating: 1,
    photoUrls: ["wrong_location.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-25T15:10:38.009+00:00",
    reviewSubject: "Wrong address delivery",
    name: null,
  },
  {
    id: 19,
    reviewBody:
      "Perfect during my COVID quarantine. Contactless delivery worked flawlessly. Lifesaver when sick!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-24T12:20:44.009+00:00",
    reviewSubject: "Great for quarantine",
    name: "Kevin Brown",
  },
  {
    id: 20,
    reviewBody:
      "Subscription auto-renewed without warning. Charged $99 when I only wanted monthly. Difficult to cancel.",
    starRating: 2,
    photoUrls: ["subscription_charge.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-23T17:35:19.009+00:00",
    reviewSubject: "Subscription issues",
    name: "Rachel White",
  },
  {
    id: 21,
    reviewBody:
      "Shopper called about every substitution. Appreciated the attention to detail! Got exactly what I wanted.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-22T14:50:27.009+00:00",
    reviewSubject: "Good communication",
    name: "Daniel Martinez",
  },
  {
    id: 22,
    reviewBody:
      "Order minimum keeps increasing. Now $35 minimum plus fees and tip. Getting too expensive for small orders.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-21T11:15:33.009+00:00",
    reviewSubject: "Increasing minimums",
    name: null,
  },
  {
    id: 23,
    reviewBody:
      "Found specialty international items I couldn't find elsewhere. Great selection for ethnic cooking ingredients.",
    starRating: 4,
    photoUrls: ["specialty_items.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-20T09:40:48.009+00:00",
    reviewSubject: "Great selection",
    name: "Priya Sharma",
  },
  {
    id: 24,
    reviewBody:
      "Driver left groceries in rain without notifying. All paper bags disintegrated, food ruined. No accountability.",
    starRating: 1,
    photoUrls: ["ruined_groceries.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-19T16:25:12.009+00:00",
    reviewSubject: "Careless delivery",
    name: "Brian Clark",
  },
  {
    id: 25,
    reviewBody:
      "Same-day delivery actually works! Ordered at 3 PM, delivered by 4:30 PM. Perfect for last-minute needs.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-18T13:30:45.009+00:00",
    reviewSubject: "Fast same-day service",
    name: "Sophia Lewis",
  },
  {
    id: 26,
    reviewBody:
      "Algorithm suggested weird item replacements. Pickles instead of olives? System needs better logic.",
    starRating: 2,
    photoUrls: ["weird_substitution.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-17T10:55:38.009+00:00",
    reviewSubject: "Bad substitutions",
    name: null,
  },
  {
    id: 27,
    reviewBody:
      "Saved my Thanksgiving! Forgot cranberry sauce and got it delivered in 45 minutes. Holiday hero!",
    starRating: 5,
    photoUrls: ["thanksgiving_save.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-16T18:40:22.009+00:00",
    reviewSubject: "Thanksgiving lifesaver",
    name: "Jennifer Hall",
  },
  {
    id: 28,
    reviewBody:
      "Refund process takes 5-7 business days. Should be instant for missing/wrong items. Cash flow problem.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-15T15:20:17.009+00:00",
    reviewSubject: "Slow refunds",
    name: "Christopher Young",
  },
  {
    id: 29,
    reviewBody:
      "Love the recipe-to-cart feature! Added all ingredients for chicken curry with one click. Brilliant!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-14T12:45:33.009+00:00",
    reviewSubject: "Great features",
    name: "Olivia King",
  },
  {
    id: 30,
    reviewBody:
      "Delivery person was rude and demanded additional tip at the door. Felt unsafe and uncomfortable.",
    starRating: 1,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-13T19:30:48.009+00:00",
    reviewSubject: "Unprofessional driver",
    name: null,
  },
  {
    id: 31,
    reviewBody:
      "Perfect for elderly parents. Set up recurring orders for them. Shopper is patient and helpful.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-12T14:15:27.009+00:00",
    reviewSubject: "Great for seniors",
    name: "Michael Scott",
  },
  {
    id: 32,
    reviewBody:
      "Received someone else's order. Contacted support, they told me to keep it but still charged me for my missing order.",
    starRating: 1,
    photoUrls: ["wrong_order.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-11T11:40:42.009+00:00",
    reviewSubject: "Wrong order mix-up",
    name: "Ashley Green",
  },
  {
    id: 33,
    reviewBody:
      "Regular promotions keep me coming back. $20 off $80 offers are actually useful, not like other services.",
    starRating: 4,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-10T09:05:19.009+00:00",
    reviewSubject: "Good promotions",
    name: "Joshua Allen",
  },
  {
    id: 34,
    reviewBody:
      "Shopper bought organic when I ordered regular, costing $15 extra. Didn't notice until charge came through.",
    starRating: 2,
    photoUrls: ["organic_vs_regular.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-09T16:50:34.009+00:00",
    reviewSubject: "Upselling without consent",
    name: null,
  },
  {
    id: 35,
    reviewBody:
      "Customer service actually solved my issue in 10 minutes! Refund processed while on chat. Impressive!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-08T13:25:48.009+00:00",
    reviewSubject: "Excellent support",
    name: "Megan Harris",
  },
  {
    id: 36,
    reviewBody:
      "Fees keep increasing every month. Now paying $12 in fees for a $40 order. Not sustainable.",
    starRating: 2,
    photoUrls: ["fee_breakdown.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-07T10:40:15.009+00:00",
    reviewSubject: "Too many fees",
    name: "Ryan Nelson",
  },
  {
    id: 37,
    reviewBody:
      "Saved my dinner party! Last-minute wine delivery arrived in 25 minutes. Guests were impressed.",
    starRating: 5,
    photoUrls: ["wine_delivery.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-06T18:15:29.009+00:00",
    reviewSubject: "Emergency delivery success",
    name: "Nicole Carter",
  },
  {
    id: 38,
    reviewBody:
      "Can't filter by dietary restrictions properly. Gluten-free search shows regular items. Needs improvement.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-05T15:30:44.009+00:00",
    reviewSubject: "Poor filtering options",
    name: null,
  },
  {
    id: 39,
    reviewBody:
      "Perfect for new moms. Ordered diapers at 2 AM when baby woke up. Delivered by 3 AM. Amazing!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-04T12:55:58.009+00:00",
    reviewSubject: "24/7 lifesaver",
    name: "Stephanie Mitchell",
  },
  {
    id: 40,
    reviewBody:
      "Items marked 'in stock' were out of stock. 6 out of 15 items unavailable. Should update inventory in real-time.",
    starRating: 2,
    photoUrls: ["out_of_stock_list.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-03T10:20:13.009+00:00",
    reviewSubject: "Inventory accuracy",
    name: "Andrew Perez",
  },
  {
    id: 41,
    reviewBody:
      "Love the group order feature! Split groceries with roommates easily. Everyone pays their share automatically.",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-11-02T17:45:27.009+00:00",
    reviewSubject: "Great for roommates",
    name: "Tyler Roberts",
  },
  {
    id: 42,
    reviewBody:
      "Shopper clearly rushed. Bag smashed my bread, eggs broken, produce bruised. No care in handling.",
    starRating: 1,
    photoUrls: ["broken_eggs.jpg", "smashed_bread.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-11-01T14:10:42.009+00:00",
    reviewSubject: "Careless packing",
    name: null,
  },
  {
    id: 43,
    reviewBody:
      "Saved 30% with digital coupons I didn't know existed. App automatically applied best deals. Smart!",
    starRating: 5,
    photoUrls: ["coupon_savings.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-31T11:35:56.009+00:00",
    reviewSubject: "Good savings",
    name: "Lauren Turner",
  },
  {
    id: 44,
    reviewBody:
      "Delivery instructions ignored every time. Clearly say 'leave at side door' but always leave at front.",
    starRating: 2,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-30T09:00:11.009+00:00",
    reviewSubject: "Instructions ignored",
    name: "Justin Phillips",
  },
  {
    id: 45,
    reviewBody:
      "Perfect during snowstorm. Didn't have to risk driving. Shopper delivered through 6 inches of snow. Hero!",
    starRating: 5,
    photoUrls: ["snow_delivery.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-29T16:25:26.009+00:00",
    reviewSubject: "Bad weather delivery",
    name: "Hannah Campbell",
  },
  {
    id: 46,
    reviewBody:
      "Receipt doesn't match store prices. Paid $4.99 for item that receipt shows $3.99. Hidden markup?",
    starRating: 2,
    photoUrls: ["price_discrepancy.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-10-28T13:50:41.009+00:00",
    reviewSubject: "Price transparency",
    name: null,
  },
  {
    id: 47,
    reviewBody:
      "Remembered my preferences from last order. Suggested items I regularly buy. Personalized experience!",
    starRating: 5,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-27T11:15:55.009+00:00",
    reviewSubject: "Smart recommendations",
    name: "Brandon Evans",
  },
  {
    id: 48,
    reviewBody:
      "Can't schedule delivery more than 3 days in advance. Need weekly recurring slot for meal planning.",
    starRating: 3,
    photoUrls: [],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-26T18:40:10.009+00:00",
    reviewSubject: "Scheduling limitations",
    name: "Kayla Collins",
  },
  {
    id: 49,
    reviewBody:
      "Found my favorite discontinued cereal! Shopper checked three stores without me asking. Above and beyond!",
    starRating: 5,
    photoUrls: ["discontinued_cereal.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: false,
    createdAt: "2025-10-25T15:05:25.009+00:00",
    reviewSubject: "Exceptional effort",
    name: "Nathan Stewart",
  },
  {
    id: 50,
    reviewBody:
      "Multiple app notifications for same update. 7 notifications about order progress. Too spammy.",
    starRating: 3,
    photoUrls: ["notification_spam.jpg"],
    email: "testrandom@gmail.com",
    reviewAsAnon: true,
    createdAt: "2025-10-24T12:30:40.009+00:00",
    reviewSubject: "Notification overload",
    name: null,
  },
];
